language: java

os:
- linux
- osx

before_install:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then jdk_switcher use oraclejdk8; fi
- rvm install 2.3.4
- rvm use 2.3.4
- export
- ruby --version
- gem --version
- gem install bundler
